### ISSUE TITLE
FILTER, dont work for me

### ISSUE THREAD

**Issue by 9acca9** [goosepirate/lox365#11]
What im doing wrong?
This is the sheet
![imagen](https://github.com/goosepirate/lox365/assets/25393371/4bb2b4f8-0173-4a71-93d3-ab3095fcb265)

There is the formula
![imagen](https://github.com/goosepirate/lox365/assets/25393371/93a2de1d-a998-4209-9bf4-b1947be84b69)

`=FILTER(A4:G32,A4:A10=I3,"")`
What can i do?
Thanks.

**Comment by goosepirate** [comment]
Are you using Ctrl + Shift + Enter when entering the formula?

**Comment by 9acca9** [comment]
I didn't know I had to enter it that way! Thanks!
