### ISSUE TITLE
function SORT issue

### ISSUE THREAD

**Issue by MRIG** [goosepirate/lox365#13]
Hi, I'v downloaded en installed the extension in LO 7.6.0.3. Function SORT is available, seems to work when selected an array, But when entered, it displays only one cel (the first one), Something is wrong with [sort index] in my case. It doesn't accept any value for colomn/row. Any idea what is wrong or what I'm doing wrong?
Thanks for the feature anyway!

Edit when used UNIQUE i got an similar issue. Only one value is displayed.
kind regards

**Comment by MRIG** [comment]
okay, I have to select the checkbox for array, my mistake, new issue I've is that after add the function I can's change/edit or delete the function

**Comment by goosepirate** [comment]
Hi. Try selecting the entire cell range that the function is using first, then edit the formula.

**Comment by MRIG** [comment]
> Hi. Try selecting the entire cell range that the function is using first, then edit the formula.

thanks, after some puzzling I got it

**Comment by goosepirate** [comment]
You're welcome.
