### ISSUE TITLE
Reverse text

### ISSUE THREAD

**Issue by Tagishsimon** [goosepirate/lox365#15]
Hi Goosepirate 

Would you consider adding another LibreOffice Calc function, ReverseText, which reverses a text string? So ABC becomes CBA.

Use case for this is explained in this thread: https://twitter.com/Tagishsimon/status/1371384451754778627 ... should say that twitter does not do a good job of displaying the whole thread; there are about 10+ tweets explaining the need; clicking on the bottom tweet will force twitter to display the next tweet.

thanks
simon

**Comment by goosepirate** [comment]
Hi. Try this formula: https://bugs.documentfoundation.org/show_bug.cgi?id=141042#c1
