### ISSUE TITLE
Cannot install on libreoffice

### ISSUE THREAD

**Issue by gyutaepark** [goosepirate/lox365#18]
![image](https://github.com/goosepirate/lox365/assets/21694989/6b133581-32f7-4b51-9a0f-d81621d2ba0e)

Currently trying to install the extension on LibreOffice 7.3.7.2 30(Build:2) yield the following error on installation.
I tried restarting the app but the functionalities are not added.

Could you help fix this issue plase?

**Comment by goosepirate** [comment]
Try LibreOffice 7.6.

**Comment by gyutaepark** [comment]
Thanks. But it seems like the installation failed on 7.6 as well.

Version:
`LibreOffice 7.6.2.1 60(Build:1)`

Error:
![image](https://github.com/goosepirate/lox365/assets/21694989/9cdf38bc-a870-4b8c-9de2-592d03e9d980)

After Restarting LibreOffice:
![image](https://github.com/goosepirate/lox365/assets/21694989/dac42745-e1b9-4793-89ce-ca04e79c7035)

When clicking Enable:
![image](https://github.com/goosepirate/lox365/assets/21694989/9e977dd4-0e26-460b-816f-bfc6b894d60d)

**Comment by ovari** [comment]
Can you please test LibreOffice 24.8? XLOOKUP and XMATCH functions will be available in the upcoming version. Please see https://wiki.documentfoundation.org/ReleaseNotes/24.8#Calc

Thank you

**Comment by ovari** [comment]
LibreOffice Help on XLOOKUP function
https://help.libreoffice.org/master/en-US/text/scalc/01/func_xlookup.html

LibreOffice issue for XLOOKUP function
https://bugs.documentfoundation.org/show_bug.cgi?id=127293

@gyutaepark does XLOOKUP in LibreOffice 24.8 work for you?

Thank you

**Comment by gyutaepark** [comment]
I'm glad that the feature is added to LibreOffice 24.8.
Unfortunately, I had already found an alternative workaround that didn't involve LibreOffice / lox365 and do not have either software installed on my machine to test it.

**Comment by ovari** [comment]
Sorry to hear you no longer have LibreOffice.

@gyutaepark could you please close this issue?

Thank you

**Comment by gyutaepark** [comment]
Thanks for checking in.
As the feature will be implemented on Libre, I'll close the issue
