### ISSUE TITLE
Will be integrated into Calc in future?

### ISSUE THREAD

**Issue by Eldenroot** [goosepirate/lox365#2]
As title says---

**Comment by goosepirate** [comment]
Thanks for asking. I'm not in the LibreOffice developer team so I could be wrong. As far as I know, XLOOKUP is planned to be added to Calc, but not FILTER, SORT, etc.

**Comment by timur-g** [comment]
Hi @goosepirate . LibreOffice developers are volunteers so you can be in the team just by submitting a code. 
XLOOKUP is now Assigned, you will be able to see the code once prepared, but there are other functions that can be added. 
I
