### ISSUE TITLE
XLOOKUP Return Value doesn't match IF test 

### ISSUE THREAD

**Issue by Marty9191** [goosepirate/lox365#21]
I'm using XLOOKUP to return a string from the return array, when it matches the lookup array.
The function successfully returns the string.
However, the string does not match an IF test in another cell

e.g.
=XLOOKUP("TEST",B2:B4,C2:C4,"ERR")	TEST	ReturnString
=ReturnString

   However, an IF function will not match "ReturnString"

**Comment by ovari** [comment]
@Marty9191 can you please test LibreOffice 24.8 or later to see if this has been resolved?

For your information, OASIS [OFFICE-4154 add XLOOKUP function](https://issues.oasis-open.org/browse/OFFICE-4154) has been implemented in [Bug 127293 - Add XLOOKUP function in Calc](https://bugs.documentfoundation.org/show_bug.cgi?id=127293) and available in [LibreOffice Calc 24.8](https://wiki.documentfoundation.org/ReleaseNotes/24.8#Calc).

Thank you

**Comment by ovari** [comment]
> This problem exists in LibreOffice 24.2.4.2.   I don't see a 24.8

### Operating Systems

LibreOffice 24.8.0 is available for the following operating systems/architectures:

* [Linux x64 (deb)](https://www.libreoffice.org/download/download-libreoffice/?type=deb-x86_64&version=24.8.0&lang=en-US)
* [Linux x64 (rpm)](https://www.libreoffice.org/download/download-libreoffice/?type=rpm-x86_64&version=24.8.0&lang=en-US)
* [macOS (Aarch64/Apple Silicon)](https://www.libreoffice.org/download/download-libreoffice/?type=mac-aarch64&version=24.8.0&lang=en-US)
* [macOS x86_64 (10.15 or newer required)](https://www.libreoffice.org/download/download-libreoffice/?type=mac-x86_64&version=24.8.0&lang=en-US)
* [Windows](https://www.libreoffice.org/download/download-libreoffice/?type=win-x86&version=24.8.0&lang=en-US)
* [Windows x86_64 (Windows 7 or newer required)](https://www.libreoffice.org/download/download-libreoffice/?type=win-x86_64&version=24.8.0&lang=en-US)

**Comment by Marty9191** [comment]
Thanks, I found it.  The problem described persists in 24.8.0.0_beta1 











---- On Tue, 02 Jul 2024 16:25:59 -0500 ovari ***@***.***> wrote ---





This problem exists in LibreOffice 24.2.4.2.   I don't see a 24.8


Operating Systems

LibreOffice 24.8.0 is available for the following operating systems/architectures:

https://www.libreoffice.org/download/download-libreoffice/?type=deb-x86_64&version=24.8.0&lang=en-US

https://www.libreoffice.org/download/download-libreoffice/?type=rpm-x86_64&version=24.8.0&lang=en-US

https://www.libreoffice.org/download/download-libreoffice/?type=mac-aarch64&version=24.8.0&lang=en-US

https://www.libreoffice.org/download/download-libreoffice/?type=mac-x86_64&version=24.8.0&lang=en-US

https://www.libreoffice.org/download/download-libreoffice/?type=win-x86&version=24.8.0&lang=en-US

https://www.libreoffice.org/download/download-libreoffice/?type=win-x86_64&version=24.8.0&lang=en-US

**Comment by ovari** [comment]
> Thanks, I found it.  The problem described persists in 24.8.0.0_beta1 

Can you please attache a sample file with a comment at https://bugs.documentfoundation.org/show_bug.cgi?id=127293?

Thank you

**Comment by Marty9191** [comment]
Correction. This problem has been corrected in 24.8.0.0_beta1. I didn't realize the the new Calc version kept the reference to the earlier xlookup function. Updated and now working. Marty













---- On Tue, 02 Jul 2024 19:46:21 -0500 Martin OToole ***@***.***> wrote ---





Thanks, I found it.  The problem described persists in 24.8.0.0_beta1 












---- On Tue, 02 Jul 2024 16:25:59 -0500 ovari ***@***.***> wrote ---











This problem exists in LibreOffice 24.2.4.2.   I don't see a 24.8


Operating Systems

LibreOffice 24.8.0 is available for the following operating systems/architectures:

https://www.libreoffice.org/download/download-libreoffice/?type=deb-x86_64&version=24.8.0&lang=en-US

https://www.libreoffice.org/download/download-libreoffice/?type=rpm-x86_64&version=24.8.0&lang=en-US

https://www.libreoffice.org/download/download-libreoffice/?type=mac-aarch64&version=24.8.0&lang=en-US

https://www.libreoffice.org/download/download-libreoffice/?type=mac-x86_64&version=24.8.0&lang=en-US

https://www.libreoffice.org/download/download-libreoffice/?type=win-x86&version=24.8.0&lang=en-US

https://www.libreoffice.org/download/download-libreoffice/?type=win-x86_64&version=24.8.0&lang=en-US

**Comment by ovari** [comment]
> Correction. This problem has been corrected in 24.8.0.0_beta1. I didn't realize the the new Calc version kept the reference to the earlier xlookup function. Updated and now working. Marty

Can you please close this issue? Thank you

**Comment by Marty9191** [comment]
This problem has been corrected in 24.8.0.0_beta1
