### ISSUE TITLE
install err

### ISSUE THREAD

**Issue by takepon1** [goosepirate/lox365#4]
Ver.4 
libreoffice 7.3 and 7.4 
install this ext.cannot install . this daialog messege.

(com.sun.star.uno.RuntimeException) { { Message = "<class 'TypeError'>: 'type' object is not subscriptable, traceback follows\X000a  File \"C:\\Program Files\\LibreOffice\\program\\pythonloader.py\", line 147, in writeRegistryInfo\X000a    mod = self.getModuleFromUrl( locationUrl )\X000a  File \"C:\\Program Files\\LibreOffice\\program\\pythonloader.py\", line 102, in getModuleFromUrl\X000a    exec(codeobject, mod.__dict__)\X000a  File \"C:\\Users\\baian\\AppData\\Roaming\\LibreOffice\\4\\user\\uno_packages\\cache\\uno_packages\\lu281968eed7m.tmp_\\Lox365 (2).oxt\\loader.py\", line 6, in <module>\X000a    class Lox365(unohelper.Base, XLox365):\X000a  File \"C:\\Users\\baian\\AppData\\Roaming\\LibreOffice\\4\\user\\uno_packages\\cache\\uno_packages\\lu281968eed7m.tmp_\\Lox365 (2).oxt\\loader.py\", line 9, in Lox365\X000a    def _get_dataarray(self, cellrange, positions: dict) -> tuple[tuple]:\X000a\X000a", Context = (com.sun.star.uno.XInterface) @0 } }

**Comment by goosepirate** [comment]
Try the latest version of Lox365. It should be fixed now.

**Comment by takepon1** [comment]
Thank you.bat
I try  Libreoffice 7.3.6.2 on windows10.lox365 ver.4.1 (del 4.1 and reinstall 4.1)
Cannot add oxt.
this err.

(com.sun.star.uno.RuntimeException) { { Message = "<class 'FileNotFoundError'>: [Errno 2] No such file or directory: 'C:\\\\Users\\\\baian\\\\AppData\\\\Roaming\\\\LibreOffice\\\\4\\\\user\\\\uno_packages\\\\cache\\\\uno_packages\\\\lu35060exfr7q.tmp_\\\\Lox365%20(3).oxt\\\\loader.py', traceback follows\X000a  File \"C:\\Program Files\\LibreOffice\\program\\pythonloader.py\", line 146, in writeRegistryInfo\X000a    mod = self.getModuleFromUrl( locationUrl )\X000a  File \"C:\\Program Files\\LibreOffice\\program\\pythonloader.py\", line 93, in getModuleFromUrl\X000a    with open( filename, encoding='utf_8' ) as fileHandle:\X000a\X000a", Context = (com.sun.star.uno.XInterface) @0 } }

**Comment by goosepirate** [comment]
You're welcome.
Try LibreOffice 7.4.

**Comment by takepon1** [comment]
Thank you.
I can install LibreOffice 7.4.3
