### ISSUE TITLE
Returning multiple columns/rows not working

### ISSUE THREAD

**Issue by tubami** [goosepirate/lox365#5]
Hello,
I try to use the function to output multiple rows. As a return array I entered a two-dimensional array (e.g. B3:C9), but as result I just get one value from the one dimensional array in column B.

**Comment by goosepirate** [comment]
Hi. Can you give an example?

**Comment by goosepirate** [comment]
I'm guessing this is no longer an issue.

**Comment by 13minutes-yt** [comment]
![image](https://github.com/goosepirate/lox365/assets/97451634/f5cc197f-c7fc-4035-b312-11bd69277935)

In xlookup it should give 2 values 1500 and 136 next to it. It is not the case here
