### ISSUE TITLE
a bug? #NAME? when "Use English function names" is enabled

### ISSUE THREAD

**Issue by githubuser181226** [goosepirate/lox365#7]
Hi.

I've found a bug.

I've installed this wonderful extension today, but when I enable "Use English function names" in Calc settings (which I really need) every lox365 function stops working and gives out #NAME? error.

Please, advise.

Edit. Found a bypass but suboptimal:
added COM.GOOSEPIRATE.LOX365.OXT. before every function name ie. COM.GOOSEPIRATE.LOX365.OXT.XLOOKUP and all is well even if "Use English function names" is activated.
it is suboptimal, though.

**Comment by goosepirate** [comment]
Lox365 already uses English function names, so this sounds like it could be an issue with Calc.
Let me know if you figure out a better way to fix this.
