### ISSUE TITLE
filter with dynamic filter value returns unexpected results

### ISSUE THREAD

**Issue by spi43984** [goosepirate/lox365#9]
I'm trying to use a value in a cell D1 as filtering value.

![image](https://github.com/goosepirate/lox365/assets/22529093/348b1566-bd3c-4bea-9a5b-f39ac6f7f0c6)

The image above shows the result for value 4. the next ones show the result for 3, 2 and 1.

![image](https://github.com/goosepirate/lox365/assets/22529093/fc046748-a436-48b8-9c0a-759dbc52d70a)
![image](https://github.com/goosepirate/lox365/assets/22529093/1e72672d-0fc4-459d-beeb-884a01371638)
![image](https://github.com/goosepirate/lox365/assets/22529093/d6930caa-abaa-4388-a305-6fe0c276e59f)

What is the correct approach to filter a list by a value that might change?

BTW - if I expand the list A2:B4 to something bigger the FILTERed list doesn't expand - I need to delete and create it from scratch.

**Comment by goosepirate** [comment]
Thanks for raising this issue. Try the latest version of Lox365. It should no longer repeat when the result is a single row.
As for expanding the output array, I don't think there is a way for an extension to do this, but you can make it large from the start.
